/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d8dadc",
        "inverse-surface": "#2d3133",
        "secondary": "#585e6c",
        "on-surface": "#191c1e",
        "inverse-on-surface": "#eff1f3",
        "secondary-container": "#dde2f3",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-tertiary-container": "#ffa77e",
        "on-primary": "#ffffff",
        "primary": "#00307d",
        "on-primary-fixed-variant": "#0040a1",
        "inverse-primary": "#b2c5ff",
        "on-secondary-fixed-variant": "#414754",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#dde2f3",
        "surface-tint": "#0056d2",
        "surface": "#f7f9fb",
        "on-secondary-fixed": "#161c27",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdbcc",
        "surface-container": "#eceef0",
        "primary-fixed-dim": "#b2c5ff",
        "surface-container-high": "#e6e8ea",
        "on-background": "#191c1e",
        "surface-container-low": "#f2f4f6",
        "primary-container": "#0045ab",
        "error": "#ba1a1a",
        "on-primary-fixed": "#001847",
        "on-secondary": "#ffffff",
        "tertiary-container": "#833301",
        "on-primary-container": "#a3bbff",
        "primary-fixed": "#dae2ff",
        "outline-variant": "#c2c6d3",
        "on-error-container": "#93000a",
        "tertiary": "#5f2200",
        "on-tertiary-fixed": "#351000",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "on-error": "#ffffff",
        "surface-variant": "#e0e3e5",
        "background": "#f7f9fb",
        "tertiary-fixed-dim": "#ffb694",
        "secondary-fixed-dim": "#c1c6d7",
        "outline": "#737783",
        "on-secondary-container": "#5e6473",
        "on-surface-variant": "#424751"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      animation: {
        'bounce-slow': 'bounce 2s infinite',
        'fade-in': 'fadeIn 0.7s ease-out',
        'slide-in-left': 'slideInLeft 0.7s ease-out',
        'slide-in-right': 'slideInRight 0.7s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideInLeft: {
          '0%': { transform: 'translateX(-30px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(30px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}