/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-dim": "var(--surface-dim)",
        "inverse-surface": "var(--inverse-surface)",
        "secondary": "var(--secondary)",
        "on-surface": "var(--on-surface)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "secondary-container": "var(--secondary-container)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "on-primary": "var(--on-primary)",
        "primary": "var(--primary)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "inverse-primary": "var(--inverse-primary)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "secondary-fixed": "var(--secondary-fixed)",
        "surface-tint": "var(--surface-tint)",
        "surface": "var(--surface)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "error-container": "var(--error-container)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "surface-container": "var(--surface-container)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "surface-container-high": "var(--surface-container-high)",
        "on-background": "var(--on-background)",
        "surface-container-low": "var(--surface-container-low)",
        "primary-container": "var(--primary-container)",
        "error": "var(--error)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "on-secondary": "var(--on-secondary)",
        "tertiary-container": "var(--tertiary-container)",
        "on-primary-container": "var(--on-primary-container)",
        "primary-fixed": "var(--primary-fixed)",
        "outline-variant": "var(--outline-variant)",
        "on-error-container": "var(--on-error-container)",
        "tertiary": "var(--tertiary)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "on-tertiary": "var(--on-tertiary)",
        "surface-bright": "var(--surface-bright)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-error": "var(--on-error)",
        "surface-variant": "var(--surface-variant)",
        "background": "#f7f9fb",
        "tertiary-fixed-dim": "#ffb694",
        "secondary-fixed-dim": "#c1c6d7",
        "outline": "#737783",
        "on-secondary-container": "#5e6473",
        "on-surface-variant": "#424751"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      animation: {
        'bounce-slow': 'bounce 2s infinite',
        'fade-in': 'fadeIn 0.7s ease-out',
        'slide-in-left': 'slideInLeft 0.7s ease-out',
        'slide-in-right': 'slideInRight 0.7s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideInLeft: {
          '0%': { transform: 'translateX(-30px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(30px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}