spring.application.name=restaurant-backend


# ==========================================
# TiDB Cloud Connection (Serverless)
# ==========================================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username={DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# ==========================================
# JPA/Hibernate avec dialecte TiDB
# ==========================================
spring.jpa.hibernate.ddl-auto=update
# Essayez d'abord TiDBDialect, sinon MySQL8Dialect
# Utilisez le dialecte moderne (Hibernate 6+)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect




# ==========================================
# Port
# ==========================================
server.port=${PORT:8080}

# ==========================================
# Timezone
# ==========================================
spring.jackson.time-zone=Indian/Antananarivo

# ==========================================
# Batch operations (performance)
# ==========================================
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=painextazzy@gmail.com
spring.mail.password=Vxsmtpsib-8b8de9df4d41f58a5869c5fe1a520a8b63ef3693d8456a14ff920c2f1c180458-FbibDa1xqJEaPrfh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.frontend.url=https://projet-springboot.vercel.app