spring.application.name=restaurant-backend


# ==========================================
# TiDB Cloud Connection (Serverless)
# ==========================================
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=root
spring.datasource.password=ruBtLtpQhFpSINxkKiyAJBAPMyRGusYA
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# ==========================================
# JPA/Hibernate avec dialecte TiDB
# ==========================================
spring.jpa.hibernate.ddl-auto=update
# Essayez d'abord TiDBDialect, sinon MySQL8Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


spring.jpa.properties.hibernate.id.new_generator_mappings=true

# ==========================================
# Port
# ==========================================
server.port=${PORT:8080}

# ==========================================
# Timezone
# ==========================================
spring.jackson.time-zone=Indian/Antananarivo

# ==========================================
# Batch operations (performance)
# ==========================================
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

