spring.application.name=restaurant-backend


# ==========================================
# TiDB Cloud Connection (Serverless)
# ==========================================
spring.datasource.url=jdbc:mysql://root:ruBtLtpQhFpSINxkKiyAJBAPMyRGusYA@turntable.proxy.rlwy.net:54953/railway
spring.datasource.username=root
spring.datasource.password=ruBtLtpQhFpSINxkKiyAJBAPMyRGusYA
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# ==========================================
# JPA/Hibernate avec dialecte TiDB
# ==========================================
spring.jpa.hibernate.ddl-auto=update
# Essayez d'abord TiDBDialect, sinon MySQL8Dialect
# Utilisez le dialecte moderne (Hibernate 6+)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect




# ==========================================
# Port
# ==========================================
server.port=${PORT:8080}

# ==========================================
# Timezone
# ==========================================
spring.jackson.time-zone=Indian/Antananarivo

# ==========================================
# Batch operations (performance)
# ==========================================
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

